//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int paymentId { get; set; }
        public int userId { get; set; }
        public string cardType { get; set; }
        public string cardNumber { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int mvcNumber { get; set; }
    
        public virtual User User { get; set; }
    }
}
